version: 2

updates:
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: master
    assignees: [AlexNDRmac]
    commit-message:
      prefix: "ci: "

  # Composer dependencies
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: master
    assignees: [AlexNDRmac]
    commit-message:
      prefix: "deps: "