name: Build

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      COMPOSER_NO_INTERACTION: 1

    strategy:
      fail-fast: false

      matrix:
        php-version:
          - '8.1'
          - '8.4'

    name: "Run with PHP ${{ matrix.php-version }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: zip
          tools: composer:v2,cs2pr
          coverage: xdebug

      - name: Get Composer Cache Dev
        id: composer-cache-dev
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache-dev.outputs.dir }}
          key: ${{ runner.os }}-composer-dev-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-dev-

      - name: Composer Install Dev
        run: |
          composer install --no-progress --prefer-dist --no-interaction --no-ansi --no-suggest --no-scripts

      - name: Run PHPCS for the codestyle
        if: always()
        run: |
          make phpcs

      - name: Run PHP Mess Detector for the code quality
        if: always()
        run: |
          make phpmd

      - name: Run PHPUnit tests
        if: always()
        run: |
          make tests

      - name: Run PHP Mutation Testing
        run: |
          git fetch origin $GITHUB_BASE_REF
          make infection \
            ARGS="--skip-initial-tests --git-diff-filter=AM --logger-github"

      - name: Generate PHP Metrics HTML report for Project
        run: |
          make metrics

      - name: Attach build artifacts to workflow
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: logs-${{ matrix.php-version }}
          path: |
            ${{ github.workspace }}/storage/logs/
            !${{ github.workspace }}/storage/logs/.gitignore
          retention-days: 1
